AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Telegram BassBoostBot

Resources:

  ## SNS TOPICS
  BassBoostTrigger:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "BassBoostTrigger"

  ## FUNCTIONS
  MsgHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MsgHandlerBassBot
      Description: "Handles message from TelegramBot"
      CodeUri: MsgHandler/
      Handler: entry.lambda_handler
      Timeout: 8
      MemorySize: 128
      Runtime: python3.7
      Layers:
        - !Ref MySqlLayer
      Policies:
        - SNSPublishMessagePolicy:
            TopicName:
              !GetAtt BassBoostTrigger.TopicName
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Events:
        BotApi:
          Type: Api
          Properties:
            Path: /
            Method: post

  BassBoostFunction:
      Type: AWS::Serverless::Function
      Properties:
        FunctionName: BassBoostBassBot
        Description: "BassBoost audio using ffmpeg layer"
        CodeUri: BassBoost/
        Handler: louder.lambda_handler
        Timeout: 40
        MemorySize: 2768
        Runtime: python3.7
        Layers:
          - !Ref ffmpegLayer
          - !Ref NumpyLayer
          - !Ref MySqlLayer
        EventInvokeConfig:
          MaximumRetryAttempts: 0
        Events:
          BassReq:
            Type: SNS
            Properties:
              Topic:
                Ref: BassBoostTrigger

  ## LAYERS
  MySqlLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: mysql_layer
      Description: python connect to mysql database
      ContentUri: layers/mysql/
      CompatibleRuntimes:
      - python3.7

  NumpyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: numpy_layer
      Description: amazon linux numpy 18.4
      ContentUri: layers/numpy/
      CompatibleRuntimes:
      - python3.7

  ffmpegLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ffmpeg_layer
      Description: ffmpeg for lambda
      ContentUri: layers/ffmpeg/
      CompatibleRuntimes:
      - python3.7
