AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

Resources:
  BassBoostTrigger:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "BassBoostTrigger"

  MailingTrigger:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "MailingTrigger"

  CredTableTBot:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: CredTableTBot
      ProvisionedThroughput:
        WriteCapacityUnits: 1
        ReadCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: cred_name
          AttributeType: S
      KeySchema:
        - KeyType: HASH
          AttributeName: cred_name

  MsgHandler:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: MsgHandlerTBot
      Description: "Handles message from @AudioBassBot"
      CodeUri: MsgHandler/
      Handler: entry.lambda_handler
      Timeout: 7
      Runtime: python3.7
      Layers:
        - mysql_layer
        - requests_layer
      Policies:
        - SNSPublishMessagePolicy:
            TopicName:
              !GetAtt BassBoostTrigger.TopicName
        - SNSPublishMessagePolicy:
            TopicName:
              !GetAtt MailingTrigger.TopicName
        - DynamoDBCrudPolicy:
            TableName:
              Ref: CredTableTBot
            
  BassBoostFunction:
      Type: AWS::Serverless::Function
      Properties:
        FunctionName: BassBoostTBot
        Description: "BassBoost audio using ffmpeg layer"
        CodeUri: BassBoost/
        Handler: louder.lambda_handler
        Timeout: 40
        MemorySize: 2768
        Runtime: python3.7
        Policies:
          - DynamoDBReadPolicy:
              TableName:
                Ref: CredTableTBot
        Layers:
          - ffmpeg_layer
          - numpy_layer
          - mysql_layer
          - requests_layer
        Events:
          BassReq:
            Type: SNS
            Properties:
              Topic:
                Ref: BassBoostTrigger

  TimeHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TimeHandlerTBot
      Description: "Update users balance every day at midnight UTC +3"
      CodeUri: TimeHandler/
      Handler: main.lambda_handler
      Timeout: 30
      Runtime: python3.7
      Layers:
        - mysql_layer
        - requests_layer
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              Ref: CredTableTBot
      Events:
        TimeEvent:
          Type: Schedule
          Properties:
            Schedule: "cron(10 21 * * ? *)"
        Mailing:
          Type: SNS
          Properties:
            Topic:
              Ref: MailingTrigger




